### ISSUE TITLE
I find a bug in this code

### ISSUE THREAD

**Issue by stpiamcee** [xuzheyuan624/slowfast-keras#4]
Class 'CenterCrop'  don't has 'randomize_parameters', and the training result is always the same. Cloud you teach me what should I do.

**Comment by Milkve** [comment]
I also met that problem, 
`WARNING:tensorflow:From train.py:75: Model.fit_generator (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
Please use Model.fit, which supports generators.
WARNING:tensorflow:sample_weight modes were coerced from
  ...
    to  
  ['...']
Traceback (most recent call last):
  File "train.py", line 84, in <module>
    train(opt)
  File "train.py", line 75, in train
    workers=opt.workers, callbacks=callbacks)
  File "/home/rbmilkve/anaconda3/envs/slowfastKeras/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/rbmilkve/anaconda3/envs/slowfastKeras/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1306, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/rbmilkve/anaconda3/envs/slowfastKeras/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/rbmilkve/anaconda3/envs/slowfastKeras/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 235, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/rbmilkve/anaconda3/envs/slowfastKeras/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 614, in _process_training_inputs
    distribution_strategy=distribution_strategy)
  File "/home/rbmilkve/anaconda3/envs/slowfastKeras/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 706, in _process_inputs
    use_multiprocessing=use_multiprocessing)
  File "/home/rbmilkve/anaconda3/envs/slowfastKeras/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 952, in __init__
    **kwargs)
  File "/home/rbmilkve/anaconda3/envs/slowfastKeras/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 747, in __init__
    peek, x = self._peek_and_restore(x)
  File "/home/rbmilkve/anaconda3/envs/slowfastKeras/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 956, in _peek_and_restore
    return x[0], x
  File "/home/rbmilkve/slowfast-keras/dataset/dataset.py", line 76, in __getitem__
    video_data, label_data = self.data_generator(batch_dataset)
  File "/home/rbmilkve/slowfast-keras/dataset/dataset.py", line 131, in data_generator
    self.spatial_transforms.randomize_parameters()
  File "/home/rbmilkve/slowfast-keras/dataset/spatial_transforms.py", line 19, in randomize_parameters
    t.randomize_parameters()
AttributeError: 'CenterCrop' object has no attribute 'randomize_parameters'
`
and my conda env contains 

`# packages in environment at /home/rbmilkve/anaconda3/envs/slowfastKeras:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_tflow_select             2.3.0                       mkl  
absl-py                   0.9.0                    py37_0  
astor                     0.8.0                    py37_0  
blas                      1.0                         mkl  
blinker                   1.4                      py37_0  
brotlipy                  0.7.0           py37h7b6447c_1000  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.15.0            h7b6447c_1001  
ca-certificates           2020.6.24                     0  
cachetools                4.1.1                    pypi_0    pypi
certifi                   2020.6.20                py37_0  
cffi                      1.14.0           py37he30daa8_1  
chardet                   3.0.4                 py37_1003  
click                     7.1.2                      py_0  
cryptography              2.9.2            py37h1ba5d50_0  
ffmpeg                    4.2.2                h20bf706_0  
freetype                  2.10.2               h5ab3b9f_0  
gast                      0.2.2                    py37_0  
gmp                       6.1.2                h6c8ec71_1  
gnutls                    3.6.5             h71b1129_1002  
google-auth               1.20.0                   pypi_0    pypi
google-auth-oauthlib      0.4.1                      py_2  
google-pasta              0.2.0                      py_0  
grpcio                    1.30.0                   pypi_0    pypi
h5py                      2.10.0           py37hd6299e0_1  
hdf5                      1.10.6               hb1b8bf9_0  
idna                      2.10                       py_0  
importlib-metadata        1.7.0                    pypi_0    pypi
intel-openmp              2020.1                      217  
jpeg                      9b                   h024ee3a_2  
keras-applications        1.0.8                      py_1  
keras-preprocessing       1.1.2                    pypi_0    pypi
lame                      3.100                h7b6447c_0  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.12.3               hd408876_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libvpx                    1.7.0                h439df22_0  
lz4-c                     1.9.2                he6710b0_1  
markdown                  3.2.2                    pypi_0    pypi
mkl                       2020.1                      217  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.1.0            py37h23d657b_0  
mkl_random                1.1.1            py37h0573a6f_0  
ncurses                   6.2                  he6710b0_1  
nettle                    3.4.1                hbb512f6_0  
numpy                     1.18.5                   pypi_0    pypi
numpy-base                1.18.5           py37hde5b4d6_0  
oauthlib                  3.1.0                      py_0  
olefile                   0.46                     py37_0  
opencv-python             4.3.0.36                 pypi_0    pypi
openh264                  2.1.0                hd408876_0  
openssl                   1.1.1g               h7b6447c_0  
opt-einsum                3.3.0                    pypi_0    pypi
opt_einsum                3.1.0                      py_0  
pillow                    7.2.0            py37hb39fc2d_0  
pip                       20.1.1                   py37_1  
protobuf                  3.12.4                   pypi_0    pypi
pyasn1                    0.4.8                      py_0  
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20                       py_2  
pyjwt                     1.7.1                    py37_0  
pyopenssl                 19.1.0                     py_1  
pysocks                   1.7.1                    py37_1  
python                    3.7.7                hcff3b4d_5  
readline                  8.0                  h7b6447c_0  
requests                  2.24.0                     py_0  
requests-oauthlib         1.3.0                      py_0  
rsa                       4.6                      pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
setuptools                49.2.0                   py37_0  
six                       1.15.0                     py_0  
sqlite                    3.32.3               h62c20be_0  
tensorboard               2.1.1                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorflow                2.1.0           mkl_py37h80a91df_0  
tensorflow-base           2.1.0           mkl_py37h6d63fb7_0  
tensorflow-estimator      2.1.0              pyhd54b08b_0  
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
urllib3                   1.25.10                  pypi_0    pypi
werkzeug                  1.0.1                      py_0  
wheel                     0.34.2                   py37_0  
wrapt                     1.12.1           py37h7b6447c_1  
x264                      1!157.20191217       h7b6447c_0  
xz                        5.2.5                h7b6447c_0  
zipp                      3.1.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0  
`
in brief, tensorflow 2.1, opencv 4.3, pillow 7.2, while cuda toolkit 10.1 and cuDNN 7.6.
I'm very noob in this field, could anyone recur this case or give me any advice?

**Comment by Milkve** [comment]
If need more error log, comment here please

**Comment by ayanasser** [comment]
The error will be solved by adding this function:
    def randomize_parameters(self):
        pass

At this class:
CenterCrop
